// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/postgres/postgres.go
//
// Generated by this command:
//
//	mockgen -package=mocks -source=./internal/postgres/postgres.go -destination=./internal/postgres/mocks/postgres.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	data "github.com/celestialdragonfly/betterreads/internal/data"
	gomock "go.uber.org/mock/gomock"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
	isgomock struct{}
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// FollowUser mocks base method.
func (m *MockAPI) FollowUser(ctx context.Context, followerID, followeeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FollowUser", ctx, followerID, followeeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// FollowUser indicates an expected call of FollowUser.
func (mr *MockAPIMockRecorder) FollowUser(ctx, followerID, followeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowUser", reflect.TypeOf((*MockAPI)(nil).FollowUser), ctx, followerID, followeeID)
}

// GetUserByID mocks base method.
func (m *MockAPI) GetUserByID(ctx context.Context, id string) (*data.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*data.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockAPIMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockAPI)(nil).GetUserByID), ctx, id)
}

// ProfileCreate mocks base method.
func (m *MockAPI) ProfileCreate(ctx context.Context, profile *data.User) (*data.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProfileCreate", ctx, profile)
	ret0, _ := ret[0].(*data.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProfileCreate indicates an expected call of ProfileCreate.
func (mr *MockAPIMockRecorder) ProfileCreate(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProfileCreate", reflect.TypeOf((*MockAPI)(nil).ProfileCreate), ctx, profile)
}

// ProfileDelete mocks base method.
func (m *MockAPI) ProfileDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProfileDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProfileDelete indicates an expected call of ProfileDelete.
func (mr *MockAPIMockRecorder) ProfileDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProfileDelete", reflect.TypeOf((*MockAPI)(nil).ProfileDelete), ctx, id)
}

// ProfileGet mocks base method.
func (m *MockAPI) ProfileGet(ctx context.Context, id string) (*data.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProfileGet", ctx, id)
	ret0, _ := ret[0].(*data.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProfileGet indicates an expected call of ProfileGet.
func (mr *MockAPIMockRecorder) ProfileGet(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProfileGet", reflect.TypeOf((*MockAPI)(nil).ProfileGet), ctx, id)
}

// ProfileUpdate mocks base method.
func (m *MockAPI) ProfileUpdate(ctx context.Context, id string, updates *data.User) (*data.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProfileUpdate", ctx, id, updates)
	ret0, _ := ret[0].(*data.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProfileUpdate indicates an expected call of ProfileUpdate.
func (mr *MockAPIMockRecorder) ProfileUpdate(ctx, id, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProfileUpdate", reflect.TypeOf((*MockAPI)(nil).ProfileUpdate), ctx, id, updates)
}

// UnfollowUser mocks base method.
func (m *MockAPI) UnfollowUser(ctx context.Context, followerID, followeeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnfollowUser", ctx, followerID, followeeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnfollowUser indicates an expected call of UnfollowUser.
func (mr *MockAPIMockRecorder) UnfollowUser(ctx, followerID, followeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnfollowUser", reflect.TypeOf((*MockAPI)(nil).UnfollowUser), ctx, followerID, followeeID)
}
